theme: jekyll-theme-cayman
title: TANS Project
description: "F. Chinu, M. Di Costanzo"
show_downloads: [true]
collections:
    docs:
      permalink: "/:collection/:path/"
      output: true
defaults:
    - scope:
        path: _docs
        type: docs
      values:
        layout: docs
github:
  home: https://bizzzio.github.io/TANS/