theme: jekyll-theme-cayman
title: [TANS Project]
description: ["F. Chinu, M. Di Costanzo"]
collections:
    docs:
      permalink: "/:collection/:path/"
      output: true
defaults:
    - scope:
        path: _docs
        type: docs
      values:
        layout: docs